export const webinarData = [
  {
    key: 15,
    linkEmbed: 'https://youtube.com/embed/IXqzrwr7sZg ', 
    title: 'Women in STEM and Space, Space Architecture',
    thumbnail: 'Images/Webinars/image/image15.png',
    speaker: '-Elif Keve',
    speakerImage: 'Images/Webinars/person/person15.png',
  },
  {
    key: 14,
    linkEmbed: 'https://youtube.com/embed/bkM3rlEADK0', 
    title: 'To Infinity and Beyond',
    thumbnail: 'Images/Webinars/image/image14.png',
    speaker: '-Gabe Gabrielle',
    speakerImage: 'Images/Webinars/person/person14.png',
  },
  {
    key: 12,
    linkEmbed: 'https://www.youtube.com/embed/Ffj6FBeiIng', 
    title: 'Moon Mania in Monsoon',
    thumbnail: 'Images/Webinars/image/image12.png',
    speaker: '-Dr. Patick Dasgupta',
    speakerImage: 'Images/Webinars/person/person12.png',
  },
  {
    key: 13,
    linkEmbed: 'https://www.youtube.com/embed/1Bcm4LO-yOs',
    title: 'The Golden Eye Opens: The James Webb Space Telescope begins',
    thumbnail: 'Images/Webinars/image/image13.png',
    speaker: '-Dr. Priya Hasan',
    speakerImage: 'Images/Webinars/person/person13.png',
  },
  {
    key: 10,
    linkEmbed: 'https://www.youtube.com/embed/QQRZE56jwZI',
    title: 'Asteroid hunting with SA Citizen Science Lab',
    thumbnail: 'Images/Webinars/image/image10.png',
    speaker: '',
    speakerImage: 'Images/Webinars/person/person10.png',
  },
  {
    key: 11,
    linkEmbed: 'https://www.youtube.com/embed/XiVdh6oj38w',
    title: 'Universe and Crypto : Uptill Now',
    thumbnail: 'Images/Webinars/image/image11.png',
    speaker: '-Suraj . SChawla',
    speakerImage: 'Images/Webinars/person/person11.png',
  },
  {
    key: 1,
    linkEmbed: 'https://www.youtube.com/embed/r_3zZ0E6Y1M',
    title: 'How to become ISRO SCientist',
    thumbnail: 'Images/Webinars/image/image1.png',
    speaker: '-RR Elan Govan',
    speakerImage: 'Images/Webinars/person/person1.png',
  },
  {
    key: 2,
    linkEmbed: 'https://www.youtube.com/embed/8iQiMBFsUy8',
    title: 'Variable Stars and the AAVSO',
    thumbnail: 'Images/Webinars/image/image2.png',
    speaker: '-Teja Begari',
    speakerImage: 'Images/Webinars/person/person2.png',
  },
  {
    key: 3,
    linkEmbed: 'https://www.youtube.com/embed/NCrA8CjO_tU',
    title: 'Human Analog Space Mission',
    thumbnail: 'Images/Webinars/image/image3.png',
    speaker: '-Eleonore Poli',
    speakerImage: 'Images/Webinars/person/person3.png',
  },
  {
    key: 4,
    linkEmbed: 'https://www.youtube.com/embed/GaUd9araJwg',
    title: 'Life Beyond Earth',
    thumbnail: 'Images/Webinars/image/image4.png',
    speaker: '-Anuj Soni',
    speakerImage: 'Images/Webinars/person/person4.png',
  },
  {
    key: 5,
    linkEmbed: 'https://www.youtube.com/embed/6x05_hOBrGQ',
    title: 'Demystifying Black Holes',
    thumbnail: 'Images/Webinars/image/image5.png',
    speaker: '-Shivika Lamba',
    speakerImage: 'Images/Webinars/person/person5.png',
  },
  {
    key: 6,
    linkEmbed: 'https://www.youtube.com/embed/Jl7FE1jwuKU',
    title: 'Citizen Science for Everyone',
    thumbnail: 'Images/Webinars/image/image6.png',
    speaker: '-Amit Raka',
    speakerImage: 'Images/Webinars/person/person6.png',
  },
  {
    key: 7,
    linkEmbed: 'https://www.youtube.com/embed/1haxTbBn3j0',
    title: 'Rad at Home India Citizen Science',
    thumbnail: 'Images/Webinars/image/image7.png',
    speaker: '-Dr. Anand Hota',
    speakerImage: 'Images/Webinars/person/person7.png',
  },
  {
    key: 8,
    linkEmbed: 'https://www.youtube.com/embed/3p0vbFi2Jh8',
    title: 'Mobile Astrophotography',
    thumbnail: 'Images/Webinars/image/image8.png',
    speaker: '-Amit Raka',
    speakerImage: 'Images/Webinars/person/person8.png',
  },
  {
    key: 9,
    linkEmbed: 'https://www.youtube.com/embed/tU7pZ5qA9QE',
    title: 'Careers after Aerospace  Eng.',
    thumbnail: 'Images/Webinars/image/image9.png',
    speaker: '-Pon Maa Kishan',
    speakerImage: 'Images/Webinars/person/person9.png',
  },
];
