export const webinarData = [
  {
    key: 23,
    linkEmbed: "https://www.youtube.com/embed/vA6SHgPGmQ0",
    title: "Peeping into cosmos through citizen science ",
    thumbnail: "/Images/Webinars/english/image/image23.png",
    speaker: "-Shubham Srivastav",
    speakerImage: "/Images/Webinars/english/person/person23.png",
    videoID: "9Uh9HfxJyZo",
    language: "english",
  },
  {
    key: 22,
    linkEmbed: "https://www.youtube.com/embed/sUR9UDDiuI",
    title: "Glimpses of Cutting Edge Astrophysics",
    thumbnail: "/Images/Webinars/english/image/image22.png",
    speaker: "-Prof. Prajval Shastri",
    speakerImage: "/Images/Webinars/english/person/person22.png",
    videoID: "9Uh9HfxJyZo",
    language: "english",
  },
  {
    key: 21,
    linkEmbed: "https://www.youtube.com/embed/l32u0AoHVwU",
    title:
      "Decoding the mysteries of the universe: Dark Energy and Dark Matter",
    thumbnail: "/Images/Webinars/english/image/image21.png",
    speaker: "-Prof. Prajval Shastri",
    speakerImage: "/Images/Webinars/english/person/person21.png",
    videoID: "9Uh9HfxJyZo",
    language: "english",
  },
  {
    key: 19,
    linkEmbed: "https://www.youtube.com/embed/9Uh9HfxJyZo",
    title: "Rocket Propulsion",
    thumbnail: "/Images/Webinars/english/image/image19.png",
    speaker: "Vani Sadadiwala",
    speakerImage: "/Images/Webinars/english/person/person19.png",
    videoID: "9Uh9HfxJyZo",
    language: "english",
  },
  {
    key: 20,
    linkEmbed: "https://www.youtube.com/embed/ovAbClBbb8s",
    title: "How to help Scientists through Citizen Science Projects",
    thumbnail: "/Images/Webinars/english/image/image20.png",
    speaker: "-Dr. Himadri Sekhar Dasn",
    speakerImage: "/Images/Webinars/english/person/person20.png",
    videoID: "ovAbClBbb8s",
    language: "english",
  },

  {
    key: 18,
    linkEmbed: "https://youtube.com/embed/RhZrf5iBVTo",
    title: "Exoplanet Exploration and Aerodymics of Aerofoil",
    thumbnail: "/Images/Webinars/english/image/image18.png",
    speaker: "-Golsar Akash",
    speakerImage: "/Images/Webinars/english/person/person18.png",
    videoID: "RhZrf5iBVTo ",
    language: "english",
  },
  {
    key: 17,
    linkEmbed: "https://youtube.com/embed/nz5XXhrked4",
    title: "CFD of Rocket Nozzles",
    thumbnail: "/Images/Webinars/english/image/image17.png",
    speaker: "-Nivedha Govindarajan",
    speakerImage: "/Images/Webinars/english/person/person17.png",
    videoID: "nz5XXhrked4",
    language: "english",
  },
  {
    key: 16,
    linkEmbed: "https://youtube.com/embed/oYM3EFKGhtI",
    title: "Nuclear physics and it’s role on Mordern Civilization",
    thumbnail: "/Images/Webinars/english/image/image16.png",
    speaker: "-Dr. Pretam Kumar Das",
    speakerImage: "/Images/Webinars/english/person/person16.png",
    videoID: "oYM3EFKGhtI",
    language: "english",
  },
  {
    key: 15,
    linkEmbed: "https://youtube.com/embed/IXqzrwr7sZg ",
    title: "Women in STEM and Space, Space Architecture",
    thumbnail: "/Images/Webinars/english/image/image15.png",
    speaker: "-Elif Keve",
    speakerImage: "/Images/Webinars/english/person/person15.png",
    videoID: "IXqzrwr7sZg",
    language: "english",
  },
  {
    key: 14,
    linkEmbed: "https://youtube.com/embed/bkM3rlEADK0",
    title: "To Infinity and Beyond",
    thumbnail: "/Images/Webinars/english/image/image14.png",
    speaker: "-Gabe Gabrielle",
    speakerImage: "/Images/Webinars/english/person/person14.png",
    videoID: "bkM3rlEADK0",
    language: "english",
  },
  {
    key: 12,
    linkEmbed: "https://www.youtube.com/embed/Ffj6FBeiIng",
    title: "Moon Mania in Monsoon",
    thumbnail: "/Images/Webinars/english/image/image12.png",
    speaker: "-Dr. Patick Dasgupta",
    speakerImage: "/Images/Webinars/english/person/person12.png",
    videoID: "Ffj6FBeiIng",
  },
  {
    key: 13,
    linkEmbed: "https://www.youtube.com/embed/1Bcm4LO-yOs",
    title: "The Golden Eye Opens: The James Webb Space Telescope begins",
    thumbnail: "/Images/Webinars/english/image/image13.png",
    speaker: "-Dr. Priya Hasan",
    speakerImage: "/Images/Webinars/english/person/person13.png",
    videoID: "1Bcm4LO-yOs",
    language: "english",
  },
  {
    key: 10,
    linkEmbed: "https://www.youtube.com/embed/QQRZE56jwZI",
    title: "Asteroid hunting with SA Citizen Science Lab",
    thumbnail: "/Images/Webinars/english/image/image10.png",
    speaker: "",
    speakerImage: "/Images/Webinars/english/person/person10.png",
    videoID: "QQRZE56jwZI",
    language: "english",
  },
  {
    key: 11,
    linkEmbed: "https://www.youtube.com/embed/XiVdh6oj38w",
    title: "Universe and Crypto : Uptill Now",
    thumbnail: "/Images/Webinars/english/image/image11.png",
    speaker: "-Suraj . SChawla",
    speakerImage: "/Images/Webinars/english/person/person11.png",
    videoID: "XiVdh6oj38w",
    language: "english",
  },
  {
    key: 1,
    linkEmbed: "https://www.youtube.com/embed/r_3zZ0E6Y1M",
    title: "How to become ISRO SCientist",
    thumbnail: "/Images/Webinars/english/image/image1.png",
    speaker: "-RR Elan Govan",
    speakerImage: "/Images/Webinars/english/person/person1.png",
    videoID: "r_3zZ0E6Y1M",
    language: "english",
  },
  {
    key: 2,
    linkEmbed: "https://www.youtube.com/embed/8iQiMBFsUy8",
    title: "Variable Stars and the AAVSO",
    thumbnail: "/Images/Webinars/english/image/image2.png",
    speaker: "-Teja Begari",
    speakerImage: "/Images/Webinars/english/person/person2.png",
    videoID: "8iQiMBFsUy8",
    language: "english",
  },
  {
    key: 3,
    linkEmbed: "https://www.youtube.com/embed/NCrA8CjO_tU",
    title: "Human Analog Space Mission",
    thumbnail: "/Images/Webinars/english/image/image3.png",
    speaker: "-Eleonore Poli",
    speakerImage: "/Images/Webinars/english/person/person3.png",
    videoID: "NCrA8CjO_tU",
    language: "english",
  },
  {
    key: 4,
    linkEmbed: "https://www.youtube.com/embed/GaUd9araJwg",
    title: "Life Beyond Earth",
    thumbnail: "/Images/Webinars/english/image/image4.png",
    speaker: "-Anuj Soni",
    speakerImage: "/Images/Webinars/english/person/person4.png",
    videoID: "GaUd9araJwg",
    language: "english",
  },
  {
    key: 5,
    linkEmbed: "https://www.youtube.com/embed/6x05_hOBrGQ",
    title: "Demystifying Black Holes",
    thumbnail: "/Images/Webinars/english/image/image5.png",
    speaker: "-Shivika Lamba",
    speakerImage: "/Images/Webinars/english/person/person5.png",
    videoID: "6x05_hOBrGQ",
    language: "english",
  },
  {
    key: 6,
    linkEmbed: "https://www.youtube.com/embed/Jl7FE1jwuKU",
    title: "Citizen Science for Everyone",
    thumbnail: "/Images/Webinars/english/image/image6.png",
    speaker: "-Amit Raka",
    speakerImage: "/Images/Webinars/english/person/person6.png",
    videoID: "Jl7FE1jwuKU",
    language: "english",
  },
  {
    key: 7,
    linkEmbed: "https://www.youtube.com/embed/1haxTbBn3j0",
    title: "Rad at Home India Citizen Science",
    thumbnail: "/Images/Webinars/english/image/image7.png",
    speaker: "-Dr. Anand Hota",
    speakerImage: "/Images/Webinars/english/person/person7.png",
    videoID: "1haxTbBn3j0",
    language: "english",
  },
  {
    key: 8,
    linkEmbed: "https://www.youtube.com/embed/3p0vbFi2Jh8",
    title: "Mobile Astrophotography",
    thumbnail: "/Images/Webinars/english/image/image8.png",
    speaker: "-Amit Raka",
    speakerImage: "/Images/Webinars/english/person/person8.png",
    videoID: "3p0vbFi2Jh8",
    language: "english",
  },
  {
    key: 9,
    linkEmbed: "https://www.youtube.com/embed/tU7pZ5qA9QE",
    title: "Careers after Aerospace  Eng.",
    thumbnail: "/Images/Webinars/english/image/image9.png",
    speaker: "-Pon Maa Kishan",
    speakerImage: "/Images/Webinars/english/person/person9.png",
    videoID: "tU7pZ5qA9QE",
    language: "english",
  },
  {
    key: Date.now(),
    linkEmbed: "https://youtube.com/embed/jTjlu4q2M7E",
    title: "সকলের জন্য মহাকাশ বিজ্ঞান",
    thumbnail: "/Images/Webinars/bengali/image/image1.png",
    speaker: "-গৌরব ব্যানার্জি",
    speakerImage: "/Images/Webinars/bengali/person/person1.png",
    videoID: "jTjlu4q2M7E",
    language: "bengali",
  },
  {
    key: Date.now(),
    linkEmbed: "https://youtube.com/embed/Dhk-pccFTY8",
    title: "কৃষ্ণগহ্বৰ আৰু ৱৰ্মহলৰ (মহাকাশীয় সুৰঙ্গৰ) আচহুৱা ৰহস্য",
    thumbnail: "/Images/Webinars/bengali/image/image2.png",
    speaker: "-অংশুমান বৰুৱা",
    speakerImage: "/Images/Webinars/bengali/person/person2.png",
    videoID: "Dhk-pccFTY8",
    language: "bengali",
  },
  {
    key: Date.now(),
    linkEmbed: "https://youtube.com/embed/jCjtvV5GvrQ",
    title: "சோலார் சிஸ்டம் ஸ்கோப்",
    thumbnail: "/Images/Webinars/tamil/image/image1.png",
    speaker: "சோலார் சிஸ்டம் ஸ்கோப்",
    speakerImage: "/Images/Webinars/tamil/person/person1.png",
    videoID: "jCjtvV5GvrQ",
    language: "tamil",
  },
];
